[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/check"
  to = "/.netlify/functions/check"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
